import type { StandardSchemaV1 } from '@standard-schema/spec'
import { CaseStateValidationError } from './errors.js'

/**
 * A typed handle to one Case as persisted: the materialized Case State plus
 * the stored bookkeeping the engine builds on.
 */
export interface CaseHandle<State> {
  /** Opaque case id generated by the storage adapter on creation. */
  id: string
  /** Name of the Case Type this case is an instance of. */
  caseTypeName: string
  /** The materialized Case State document, validated against the schema. */
  state: State
  /** Per-case monotonic sequence counter, 0 at creation, bumped by every committed Execution. */
  seq: number
  /** Dormancy marker set by `end()`; null while the case is active. */
  endedAt: Date | null
  createdAt: Date
  updatedAt: Date
}

/**
 * Validate a document against a state schema, loudly. The one implementation
 * of "this document must satisfy this schema or the caller hears about it" —
 * `resolve.ts` layers the case-type registry on top of it, and everything
 * that validates a Case State goes through one of the two.
 */
export const validateAgainstSchema = async <S extends StandardSchemaV1>(
  schema: S,
  value: unknown,
  context: string,
): Promise<StandardSchemaV1.InferOutput<S>> => {
  const result = await schema['~standard'].validate(value)
  if (result.issues) throw new CaseStateValidationError(context, result.issues)
  return result.value as StandardSchemaV1.InferOutput<S>
}

/** An unvalidated persisted record; core resolves its definition before use. */
export type StoredCase = CaseHandle<unknown>

export type Dormancy = 'ended' | 'reopened'
