import type { StandardSchemaV1 } from '@standard-schema/spec'
import { FRAMEWORK_SCHEMA } from './bootstrap.js'
import { CaseNotFoundError, CaseStateValidationError } from './errors.js'
import { mintId } from './ids.js'
import type { Queryable, Transaction } from './queryable.js'

const CASES = `${FRAMEWORK_SCHEMA}.cases`
const CASE_COLUMNS =
  'id, case_type, state, seq, ended_at, created_at, updated_at'

/**
 * A typed handle to one Case as persisted: the materialized Case State plus
 * the row-level bookkeeping the engine builds on.
 */
export interface CaseHandle<State> {
  /** Case id — a UUID generated by the store on creation. */
  id: string
  /** Name of the Case Type this case is an instance of. */
  caseTypeName: string
  /** The materialized Case State document, validated against the schema. */
  state: State
  /** Per-case monotonic sequence counter, 0 at creation, bumped by every committed Execution. */
  seq: number
  /** Dormancy marker set by `end()`; null while the case is active. */
  endedAt: Date | null
  createdAt: Date
  updatedAt: Date
}

/** Row shape of `affordance.cases` (int8 arrives as text from the pg driver). */
type CaseRow = {
  id: string
  case_type: string
  state: unknown
  seq: string | number
  ended_at: Date | null
  created_at: Date
  updated_at: Date
}

const toHandle = <State>(row: CaseRow, state: State): CaseHandle<State> => ({
  id: row.id,
  caseTypeName: row.case_type,
  state,
  // Number() is safe: seq counts executions of one human-paced case and will
  // never approach 2^53.
  seq: Number(row.seq),
  endedAt: row.ended_at,
  createdAt: row.created_at,
  updatedAt: row.updated_at,
})

/**
 * Validate a document against a state schema, loudly. The one implementation
 * of "this document must satisfy this schema or the caller hears about it" —
 * `resolve.ts` layers the case-type registry on top of it, and everything
 * that validates a Case State goes through one of the two.
 */
export const validateAgainstSchema = async <S extends StandardSchemaV1>(
  schema: S,
  value: unknown,
  context: string,
): Promise<StandardSchemaV1.InferOutput<S>> => {
  const result = await schema['~standard'].validate(value)
  if (result.issues) throw new CaseStateValidationError(context, result.issues)
  return result.value as StandardSchemaV1.InferOutput<S>
}

/**
 * `createCase` against an explicit {@link Queryable} — the shared-transaction
 * seam. State is stringified explicitly so array-rooted documents are stored
 * as jsonb rather than misread as Postgres arrays.
 */
export const insertCase = async <S extends StandardSchemaV1>(
  db: Queryable,
  caseTypeName: string,
  stateSchema: S,
  initialState: StandardSchemaV1.InferInput<S>,
): Promise<CaseHandle<StandardSchemaV1.InferOutput<S>>> => {
  const state = await validateAgainstSchema(
    stateSchema,
    initialState,
    'initial state',
  )
  const id = mintId('case')
  const { rows } = await db.query<CaseRow>(
    `insert into ${CASES} (id, case_type, state)
     values ($1, $2, $3::jsonb)
     returning ${CASE_COLUMNS}`,
    [id, caseTypeName, JSON.stringify(state)],
  )
  const row = rows[0]
  if (!row) throw new Error(`insert into ${CASES} returned no row`)
  return toHandle(row, state)
}

/** `loadCase` against an explicit {@link Queryable} — the shared-transaction seam. */
export const selectCase = async <S extends StandardSchemaV1>(
  db: Queryable,
  id: string,
  stateSchema: S,
): Promise<CaseHandle<StandardSchemaV1.InferOutput<S>>> => {
  const handle = await selectCaseUntyped(db, id)
  const state = await validateAgainstSchema(
    stateSchema,
    handle.state,
    'stored state',
  )
  return { ...handle, state }
}

/**
 * Load a Case by id with the stored state **unvalidated** (`unknown`).
 *
 * Additive export for the engine: the engine learns which state
 * schema applies only *from* the loaded row — `case_type` names the
 * registered case type — so it must read the row before it can validate.
 * Every other caller should prefer {@link selectCase} / `loadCase`, which
 * validate; whoever consumes this handle owns validating `state` against the
 * type's schema before trusting it.
 */
export const selectCaseUntyped = async (
  db: Queryable,
  id: string,
): Promise<CaseHandle<unknown>> => {
  const { rows } = await db.query<CaseRow>(
    `select ${CASE_COLUMNS} from ${CASES} where id = $1`,
    [id],
  )
  const row = rows[0]
  if (!row) throw new CaseNotFoundError(id)
  return toHandle(row, row.state)
}

/**
 * Load a Case by id **for update** — `select … for update`, so the row lock is
 * held until the calling transaction ends.
 *
 * This is the execution lifecycle's serialization point: the claim and the
 * commit both take the case row's lock first, which is what makes the
 * one-in-flight-execution check (and an expired claim's takeover) a decision
 * no two transactions can make concurrently.
 */
export const selectCaseForUpdate = async (
  tx: Transaction,
  id: string,
): Promise<CaseHandle<unknown>> => {
  const { rows } = await tx.query<CaseRow>(
    `select ${CASE_COLUMNS} from ${CASES} where id = $1 for update`,
    [id],
  )
  const row = rows[0]
  if (!row) throw new CaseNotFoundError(id)
  return toHandle(row, row.state)
}

/** The dormancy transition a committing Execution applies to the case row (`end()` / `reopen()`). */
export type Dormancy = 'ended' | 'reopened'

/**
 * Write the next Case State, bump `seq`, and apply the Execution's dormancy
 * transition, if any: `'ended'` stamps `ended_at`, `'reopened'` clears it,
 * `null` leaves it exactly as it was. The state document is **not** validated
 * here — the execution lifecycle validates the handler's return against the
 * case type's schema before calling this, and reports a failure there.
 */
export const updateCaseState = async (
  tx: Transaction,
  id: string,
  state: unknown,
  dormancy: Dormancy | null = null,
): Promise<CaseHandle<unknown>> => {
  const { rows } = await tx.query<CaseRow>(
    `update ${CASES}
     set state = $2::jsonb,
         seq = seq + 1,
         ended_at = case
           when $3::text = 'ended' then now()
           when $3::text = 'reopened' then null
           else ended_at
         end,
         updated_at = now()
     where id = $1
     returning ${CASE_COLUMNS}`,
    [id, JSON.stringify(state), dormancy],
  )
  const row = rows[0]
  if (!row) throw new CaseNotFoundError(id)
  return toHandle(row, row.state)
}
